// Phononic Bandgap Designer/frontend/src/components/PresetSelector.svelte
<script lang="ts">
    import type { Preset } from '../types';

    export let presets: Preset[];
    export let onSelect: (preset: Preset) => void;
</script>

<div class="preset-selector">
    <div class="preset-header">
        <h3>🎯 快速预设</h3>
        <span class="preset-hint">点击加载预设场景</span>
    </div>
    <div class="preset-grid">
        {#each presets as preset}
            <button class="preset-card" on:click={() => onSelect(preset)}>
                <div class="preset-icon">
                    {#if preset.id === 'square-2d'}
                        ⬜
                    {:else if preset.id === 'diamond-3d'}
                        💎
                    {:else if preset.id === 'gradient-index'}
                        🔮
                    {:else if preset.id === 'topological-edge'}
                        🌀
                    {:else}
                        📦
                    {/if}
                </div>
                <div class="preset-info">
                    <span class="preset-name">{preset.name}</span>
                    <span class="preset-description">{preset.description}</span>
                </div>
            </button>
        {/each}
    </div>
</div>

<style>
    .preset-selector {
        padding: 15px 30px;
        background: rgba(0, 0, 0, 0.2);
        border-bottom: 1px solid rgba(255, 255, 255, 0.05);
    }

    .preset-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 12px;
    }

    .preset-header h3 {
        margin: 0;
        font-size: 1rem;
        color: #00d4ff;
    }

    .preset-hint {
        font-size: 0.8rem;
        color: #666;
    }

    .preset-grid {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 12px;
    }

    .preset-card {
        display: flex;
        align-items: center;
        gap: 12px;
        padding: 12px 16px;
        background: rgba(255, 255, 255, 0.05);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 10px;
        cursor: pointer;
        transition: all 0.3s ease;
        text-align: left;
    }

    .preset-card:hover {
        background: rgba(123, 47, 247, 0.15);
        border-color: rgba(123, 47, 247, 0.4);
        transform: translateY(-2px);
    }

    .preset-icon {
        font-size: 1.5rem;
    }

    .preset-info {
        display: flex;
        flex-direction: column;
        gap: 3px;
    }

    .preset-name {
        font-size: 0.85rem;
        font-weight: 600;
        color: #fff;
    }

    .preset-description {
        font-size: 0.7rem;
        color: #888;
    }
</style>

// Polygon Boolean & Parametric Modeler/frontend/src/PresetSelector.jsx
function PresetSelector(props) {
  const presets = [
    {
      id: 'preset1',
      name: '预设一',
      title: '共线边界的退化多边形合并',
      description: '演示共线边的重复合并与数值容差导致的微小缝隙',
      icon: '📐',
      color: '#3498db'
    },
    {
      id: 'preset2',
      name: '预设二',
      title: '自交多边形的非简单区域解析',
      description: '演示自交多边形的处理和自交点旋转标记',
      icon: '🔄',
      color: '#e74c3c'
    },
    {
      id: 'preset3',
      name: '预设三',
      title: '多点切触的奇异接触判定',
      description: '演示多个接触点的奇异边界处理和闪烁动画',
      icon: '⚡',
      color: '#f39c12'
    },
    {
      id: 'preset4',
      name: '预设四',
      title: '孔洞多边形差集运算的相反方向错误',
      description: '演示孔洞方向错误导致的内外反转问题',
      icon: '🕳️',
      color: '#9b59b6'
    }
  ];

  return (
    <div style={{ marginBottom: '20px' }}>
      <h3 style={{ margin: '0 0 15px 0', color: '#f39c12' }}>🎬 预设场景</h3>
      
      <div style={{ display: 'flex', 'flex-direction': 'column', gap: '10px' }}>
        {presets.map(preset => (
          <button
            key={preset.id}
            onClick={() => props.onLoadPreset(preset.id)}
            style={{
              padding: '12px',
              border: 'none',
              'border-radius': '8px',
              cursor: 'pointer',
              background: 'rgba(255, 255, 255, 0.05)',
              color: 'white',
              'font-size': '13px',
              'text-align': 'left',
              transition: 'all 0.3s',
              'border-left': `4px solid ${preset.color}`
            }}
            onMouseOver={(e) => {
              e.currentTarget.style.background = 'rgba(255, 255, 255, 0.1)';
            }}
            onMouseOut={(e) => {
              e.currentTarget.style.background = 'rgba(255, 255, 255, 0.05)';
            }}
          >
            <div style={{ display: 'flex', 'align-items': 'center', gap: '8px', 'margin-bottom': '4px' }}>
              <span style={{ 'font-size': '18px' }}>{preset.icon}</span>
              <span style={{ 'font-weight': 'bold', color: preset.color }}>{preset.name}</span>
            </div>
            <div style={{ 'font-size': '12px', color: '#ccc', 'margin-left': '26px' }}>
              {preset.title}
            </div>
            <div style={{ 'font-size': '11px', color: '#888', 'margin-left': '26px', 'margin-top': '4px' }}>
              {preset.description}
            </div>
          </button>
        ))}
      </div>
    </div>
  );
}

export default PresetSelector;
